RBMK = RBMK or {}

RBMK.CELL_FUEL = 1
RBMK.CELL_STEAM = 2
RBMK.CELL_CONTROL = 3
RBMK.CELL_REFLECTOR = 4
RBMK.CELL_BLANK = 5
RBMK.CELL_AUTOROD = 6
RBMK.CELL_SOURCE = 7

RBMK.CellSymbols = {

    [RBMK.CELL_BLANK] = 'B',
    [RBMK.CELL_FUEL] = 'F',
    [RBMK.CELL_STEAM] = 'S',
    [RBMK.CELL_CONTROL] = 'C',
    [RBMK.CELL_REFLECTOR] = 'R',
    [RBMK.CELL_AUTOROD] = 'A',
    [RBMK.CELL_SOURCE] = 'N'

}