local MAP = LUASQUARE_MAP
MAP.RegisterPackage('powerplant', {load = function()
    include('luasquare_powerplant/init.lua')
    include('luasquare_powerplant/catalog.lua')
    include('luasquare_powerplant/components.lua')
end})
MAP.RegisterPackage('rbmk', {requires = {'powerplant'}, load = function()
    include('luasquare_rbmk/init.lua')
    include('luasquare_rbmk/components.lua')
    include('luasquare_rbmk/presentation.lua')
end})
MAP.RegisterPackage('instruments', {load = function()
    include('luasquare_module/seg7display.lua')
    include('luasquare_module/gaugedisplay.lua')
    include('luasquare_module/map/instruments.lua')
end})
MAP.RegisterPackage('source', {load = function()
    include('luasquare_module/sourcebinding.lua')
    include('luasquare_module/machinery.lua')
    include('luasquare_module/map/bindings.lua')
end})
MAP.RegisterPackage('presentation', {load = function()
    include('luasquare_module/3d2display/engine.lua')
    include('luasquare_module/timeline/engine.lua')
    include('luasquare_module/audio/engine.lua')
    include('luasquare_module/annunciator/engine.lua')
    include('luasquare_module/control/engine.lua')
    include('luasquare_module/map/sources.lua')
end})
